name: VICO Code Llama 13B
version: 1.5.0
schema: v1
models:
  - name: Code Llama 13B Instruct
    provider: ollama
    model: codellama:13b-instruct
    apiBase: http://localhost:10002
    roles:
      - chat
      - edit
      - apply
  - name: Code Llama 13B Code
    provider: ollama
    model: codellama:13b-code
    apiBase: http://localhost:10002
    roles:
      - autocomplete
  - name: Nomic Embed Code
    provider: ollama
    model: hf.co/nomic-ai/nomic-embed-code-GGUF:Q4_K_M
    apiBase: http://localhost:10002
    roles:
      - embed
context:
  - provider: code
  - provider: docs
  - provider: diff
  - provider: terminal
  - provider: problems
  - provider: folder
  - provider: codebase
