name: VICO Qwen 2.5 Coder 3B
version: 1.3.2
schema: v1
models:
  - name: Qwen 2.5 Coder 3B Instruct
    provider: ollama
    model: qwen2.5-coder:3b-instruct
    apiBase: http://localhost:10002
    roles:
      - chat
      - edit
      - apply
  - name: Qwen 2.5 Coder 3B Base
    provider: ollama
    model: qwen2.5-coder:3b-base
    apiBase: http://localhost:10002
    roles:
      - autocomplete
  - name: Nomic Embed Text v1.5
    provider: ollama
    model: nomic-embed-text:v1.5
    apiBase: http://localhost:10002
    roles:
      - embed
context:
  - provider: code
  - provider: docs
  - provider: diff
  - provider: terminal
  - provider: problems
  - provider: folder
  - provider: codebase
