name: VICO CodeGemma 7B
version: 1.4.0
schema: v1
models:
  - name: CodeGemma 7B Instruct
    provider: ollama
    model: codegemma:7b-instruct
    apiBase: http://localhost:10002
    roles:
      - chat
      - edit
      - apply
  - name: CodeGemma 7B Code
    provider: ollama
    model: codegemma:7b-code
    apiBase: http://localhost:10002
    roles:
      - autocomplete
  - name: Nomic Embed Code
    provider: ollama
    model: hf.co/nomic-ai/nomic-embed-code-GGUF:Q4_K_M
    apiBase: http://localhost:10002
    roles:
      - embed
context:
  - provider: code
  - provider: docs
  - provider: diff
  - provider: terminal
  - provider: problems
  - provider: folder
  - provider: codebase
