services:
  webui:
    image: ghcr.io/open-webui/open-webui:v0.6.16
    ports:
      - 10000:8080
    volumes:
      - ./volumes/webui:/app/backend/data
    environment:
      WEBUI_AUTH: False
      ENABLE_CODE_EXECUTION: False
      ENABLE_CODE_INTERPRETER: False
      ENABLE_EVALUATION_ARENA_MODELS: False
      OLLAMA_BASE_URL: http://ollama:11434
      RAG_EMBEDDING_ENGINE: ollama
      RAG_EMBEDDING_MODEL: nomic-embed-text:v1.5

  mkdocs:
    image: squidfunk/mkdocs-material:9.6.15
    ports:
      - 10001:8000
    volumes:
      - ./docs:/docs/docs
      - ./mkdocs.yml:/docs/mkdocs.yml
      - ./volumes/mkdocs:/docs/.cache

  ollama:
    image: ollama/ollama:0.9.6
    ports:
      - 10002:11434
    volumes:
      - ./volumes/ollama:/root/.ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
