services:
  mkdocs:
    image: squidfunk/mkdocs-material:9.6.16
    ports:
      - 12300:8000
    volumes:
      - ./docs:/docs/docs
      - ./mkdocs.yml:/docs/mkdocs.yml
      - ./volumes/mkdocs:/docs/.cache

  webui:
    image: ghcr.io/open-webui/open-webui:v0.6.18
    gpus: all
    ports:
      - 12301:8080
    volumes:
      - ./volumes/webui:/app/backend/data
    environment:
      WEBUI_AUTH: False
      OFFLINE_MODE: True
      # ENABLE_CODE_EXECUTION: False
      # ENABLE_CODE_INTERPRETER: False
      # ENABLE_AUTOCOMPLETE_GENERATION: False
      # ENABLE_EVALUATION_ARENA_MODELS: False
      OLLAMA_BASE_URL: http://ollama:11434
      RAG_EMBEDDING_ENGINE: ollama
      RAG_EMBEDDING_MODEL: snowflake-arctic-embed2:568m

  ollama:
    image: ollama/ollama:0.10.1
    gpus: all
    ports:
      - 12302:11434
    volumes:
      - ./volumes/ollama:/root/.ollama
    environment:
      OLLAMA_NUM_PARALLEL: 1
      OLLAMA_MAX_LOADED_MODELS: 1
