services:
  mkdocs:
    image: squidfunk/mkdocs-material:9.6.15
    ports:
      - 12300:8000
    volumes:
      - ./docs:/docs/docs
      - ./mkdocs.yml:/docs/mkdocs.yml
      - ./volumes/mkdocs:/docs/.cache

  webui:
    image: ghcr.io/open-webui/open-webui:v0.6.16
    ports:
      - 12301:8080
    volumes:
      - ./volumes/webui:/app/backend/data
    environment:
      WEBUI_AUTH: False
      OLLAMA_BASE_URL: http://ollama:11434
      RAG_EMBEDDING_ENGINE: ollama
      RAG_EMBEDDING_MODEL: mxbai-embed-large:335m

  ollama:
    image: ollama/ollama:0.9.6
    ports:
      - 12302:11434
    volumes:
      - ./volumes/ollama:/root/.ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
